version : '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: somewordpress
        MYSQL_USER: somewordpress
        MYSQL_PASSWORD: somewordpress
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      ="80000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: somewordpress
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: somewordpress

volumes:
  db_data : {}
